### Register - local
POST http://localhost:3080/auth/register
Content-Type: application/json 

{
    "email": "example+alice@gmail.com",
    "enc_password": "$2a$10$SvdYZv5Alws3WSMfF1pw8eYsiwvdFGBaC3Z.bwfOz5Dq0A9bAZiIO",
    "firstName": "Alice",
    "lastName": "Page",
    "userName": "alice5",
    "birth_date": "2000-01-01"
}

### Login - local
POST http://localhost:3080/auth/login
Content-Type: application/json 

{
    "email": "example+alice@gmail.com",
    "raw_password": "validPassword#2"
}

### Login - local
POST http://localhost:3080/auth/login
Content-Type: application/json 

{
    "email": "example+1@gmail.com",
    "raw_password": "validPassword#1"
}

### Login - local
GET http://127.0.0.1:3080/user/get_all_users_infos

### Login - local
POST http://127.0.0.1:3080/user/get_user_info_by_email
Content-Type: application/json 

{
    "email": "example+1@gmail.com"
}