### ---------- Auth Path - Jessica ------------
### Register
POST http://localhost:3080/auth/register
Content-Type: application/json 

{
    "email": "example+jessica@gmail.com",
    "enc_password": "$2a$10$EibSJ9JN16VgWJFhPlfVZOxMHdSJLuGU3bMfoyplJDRNsvBvcaV6e",
    "firstName": "Jessica",
    "lastName": "Alexandrov",
    "userName": "jessica_goldheart21",
    "birth_date": "2000-12-12"
}

### Login
POST http://localhost:3080/auth/login
Content-Type: application/json 

{
    "email": "example+jessica@gmail.com",
    "raw_password": "validPassword#1"
}

### Delete Account
POST http://localhost:3080/auth/deleteaccount
Content-Type: application/json 

{
    "email": "example+jessica@gmail.com",
    "raw_password": "validPassword#1",
    "delete_confirmation": "deletemyaccount"
}


### ---------- User Path ------------
### get_all_users_infos 
GET http://localhost:3080/user/get_all_users_infos

### get_user_info_by_email
POST http://localhost:3080/user/get_user_info_by_email
Content-Type: application/json 

{
    "email": "example+jessica@gmail.com"
}

### ---------- Posts Path ------------

### create 
POST http://localhost:3080/post/create
Content-Type: application/json 

{
    "post_tittle": "Very cheap jewelerry. (Jessica's)",
    "post_text": "Very long and beautiful explanation about my beautiful cheap jewelerry. Then my cat walk on keyboardd kjaeriluhf3 4598y4wg59p8y4g p9y8 4g5089yu 4g5098 r5g0pu9 jr45p98 w4r9h8eup !!!",
    "author_email": "example+jessica@gmail.com",
    "starting_price": 40,
    "publication_time": "2023-06-13",
    "expiration_time": "2023-08-13"
}

### get_all_posts
GET http://localhost:3080/post/get_all_posts

### get_all_posts_by_author
POST http://localhost:3080/post/get_all_posts_by_author
Content-Type: application/json 

{
    "email": "example+jessica@gmail.com"
}

### get_post_by_id
POST http://localhost:3080/post/get_post_by_id
Content-Type: application/json 

{
    "post_id": "6488fbd516db2992eaa3d511"
}

### get_20_newest_posts


### get_post_by_id WORKSSSSSSSSSSSSSSS
POST http://localhost:3080/post/update_post_by_id
Content-Type: application/json 

{
    "_id": "6488fbd516db2992eaa3d511",
    "post_tittle": "abc123",
    "leading_buyer_email": "abc123",
    "new_price": "480"
}





### ---------- Notes ------------

