### ---------- Auth Path - alice ------------
### Register
POST http://localhost:3080/auth/register
Content-Type: application/json 

{
    "email": "example+alice@gmail.com",
    "enc_password": "$2a$10$EibSJ9JN16VgWJFhPlfVZOxMHdSJLuGU3bMfoyplJDRNsvBvcaV6e",
    "firstName": "Alice",
    "lastName": "Page",
    "userName": "alice5",
    "birth_date": "2000-01-01"
}

### Login
POST http://localhost:3080/auth/login
Content-Type: application/json 

{
    "email": "example+alice@gmail.com",
    "raw_password": "validPassword#1"
}

### Delete Account
POST http://localhost:3080/auth/deleteaccount
Content-Type: application/json 

{
    "email": "example+alice@gmail.com",
    "raw_password": "validPassword#1",
    "delete_confirmation": "deletemyaccount"
}


### ---------- User Path ------------
### get_all_users_infos 
GET http://localhost:3080/user/get_all_users_infos

### get_user_info_by_email
POST http://localhost:3080/user/get_user_info_by_email
Content-Type: application/json 

{
    "email": "example+alice@gmail.com"
}



### edit_info XXXXXXXXXXXXXXXXXXXXXX
POST http://localhost:3080/user/edit_info
Content-Type: application/json 

{
    "email": "example+alice@gmail.com"
}

### ---------- Posts Path ------------

### create 
POST http://localhost:3080/post/create
Content-Type: application/json 

{
    "post_tittle": "The computer's motherboard.",
    "post_text": "Very long and beautiful explanation about my computer's motherboard for sale. Then my bestfriend's cat walk on keyboardd khi s drfgkluh dsfrvg kulh dsrg kul hsdrtfg ilug dfr tvliug sdrt g 87ilre54t !!!",
    "author_email": "example+alice@gmail.com",
    "starting_price": 200,
    "publication_time": "2023-06-13",
    "expiration_time": "2023-08-13"
}

### get_all_posts
GET http://localhost:3080/post/get_all_posts

### get_all_posts_by_author
POST http://localhost:3080/post/get_all_posts_by_author
Content-Type: application/json 

{
    "email": "example+alice@gmail.com"
}

### get_post_by_id
### get_20_newest_posts








### ---------- Notes ------------
POST http://localhost:3080/user/edit_info
Content-Type: application/json

{
     "email": "12@walla.com",
      "existEmail": "eu@walla.com",
      "enc_password": "$2a$10$qyb5xURTtGeC7m/byU1Rx.hmWBomYMhqhMDLHGRx5Odz.416zNjkC",
      "firstName": "fanny",
      "lastName": "lastName",
      "userName": "username",
      "birth_date": "2000-01-01"
}


### follow
POST http://localhost:3080/user/follow
Content-Type: application/json

{
    "active_user_email": "example+alice@gmail.com",
    "target_email": "example+dave@gmail.com"
}


### isfollowing
POST http://localhost:3080/user/isfollowing
Content-Type: application/json

{
    "active_user_email": "example+alice@gmail.com",
    "target_email": "example+dave@gmail.com"
}

### unfollow
POST http://localhost:3080/user/unfollow
Content-Type: application/json

{
    "active_user_email": "example+alice@gmail.com",
    "target_email": "example+dave@gmail.com"
}
